### ISSUE TITLE
Create giving jsondecodeerror

### ISSUE THREAD

**Issue by aflack143** [aflack143/world_spectacular_backend#1]
[Link for Frontend React Repository](https://github.com/aflack143/world_spectacular_frontend)<br>
[Link for Backend Django Repository](https://github.com/aflack143/world_spectacular_backend)

My create is not decoding correctly.

I can print the parsed_body and it displays my data, so its sending it over correctly. But the profiles/create/ is not rendering for me to actually create a user from react (but I was able create a user through admin).

![image](https://user-images.githubusercontent.com/80013194/125681786-cdc50172-c4d7-4bc8-97d5-bb9b66385a25.png)
![image](https://user-images.githubusercontent.com/80013194/125681813-444c68e5-d23e-4b8c-82ff-d0b297a9ef02.png)

I have gotten a bunch of different errors while trying alternate things to pass data, but since the data is passing in the request I am now stumped how to import it, the code looks like what we did in skynet for creating a tweet. I am not doing anything special with passwords, just calling over their auth0 sub.

Please help me get this to create.

**Comment by davidmagbee** [comment]
What resources have you utilized thus far to dig into this issue? @aflack143

**Comment by CRHarding** [comment]
Also I'm not seeing any of your profiles/create route set up, we need to have all the most recent code pushed so that we can test locally and see what's going on. Even if they code isn't working it's super helpful for us to be able to clone down and see the error ourselves @aflack143

**Comment by aflack143** [comment]
https://stackoverflow.com/questions/41309185/flask-json-json-decoder-jsondecodeerror-expecting-value-line-1-column-1-char
https://stackoverflow.com/questions/16573332/jsondecodeerror-expecting-value-line-1-column-1-char-0
https://www.youtube.com/watch?v=StwpqfYF3Kk

**Comment by aflack143** [comment]
I just got the backend to push after 15+ minutes, sorry for the delay.

**Comment by CRHarding** [comment]
Ok, I'm seeing in your frontend code you have a commented out {data: profile} in your handleSubmit (CreateProfile.js line 43)...which could be messing things up a bit. Can you try throwing a print(request.body) in your django code in the create_user function (views.py line 49) and letting us know the output in your django terminal?

**Comment by aflack143** [comment]
![image](https://user-images.githubusercontent.com/80013194/125686273-cc7f1855-b9ad-48e5-9340-61ad69ee5888.png) but I still get the error on the profile/create/ screen and in the Scripts

**Comment by CRHarding** [comment]
Can you try taking out the commented out line in the rreact code (line 43)?

**Comment by aflack143** [comment]
with the print(request.body):
![image](https://user-images.githubusercontent.com/80013194/125686849-c82d4b91-a73a-4211-90d3-a10a60ee4de4.png)

**Comment by davidmagbee** [comment]
For my own sanity... can you delete the extra space in the `views.py` on `line 48` for the `def create_user(request)`?

**Comment by aflack143** [comment]
updated code pushed

**Comment by CRHarding** [comment]
The interesting thing to me is that the function still runs, so your backend is correctly printing. What happens if you try to save the data, does it save to your database?

**Comment by aflack143** [comment]
![image](https://user-images.githubusercontent.com/80013194/125689974-7d54c4a8-15d3-4224-b321-f3e8ce9e2268.png)

**Comment by CRHarding** [comment]
Can you try, in your react app, setting the token to something like "helloworld" no spaces?

**Comment by aflack143** [comment]
I get the same error after fixing the def create_user(request)

**Comment by CRHarding** [comment]
So in CreateProfile.js file line 14 just have the token: "helloworld"

**Comment by aflack143** [comment]
![image](https://user-images.githubusercontent.com/80013194/125690813-47105aa9-f062-49f5-9ad0-15432874f84c.png)

**Comment by CRHarding** [comment]
This seems silly but maybe it'll work, worth a shot, can you change the single quotes to double quotes inside the user = User line?

**Comment by aflack143** [comment]
same issue of keyerror: 'token'

**Comment by CRHarding** [comment]
Ahhhh, I think we're getting somewhere!

**Comment by CRHarding** [comment]
Ok, so you have user = User(token=parsed_body['token'] but your parsed_body is still a dictionary with one key, 'data', and the value of that key being all the data you need. So you should be able to do something like parsed_body = parsed_body['data']

**Comment by CRHarding** [comment]
@aflack143 give it a shot and hopefully this narrows things down a little!

**Comment by aflack143** [comment]
![image](https://user-images.githubusercontent.com/80013194/125692953-7b7e44d7-5728-4325-b6ba-cd09310a56e9.png)

**Comment by CRHarding** [comment]
Ah, no, I meant above that line have parsed_body = parsed_body['data'] and then inside of the User() line keep everything the same.

**Comment by aflack143** [comment]
![image](https://user-images.githubusercontent.com/80013194/125693293-d5aa880e-b6c2-449b-b863-6e27caccef7c.png)

**Comment by CRHarding** [comment]
Can you push your updated code?

**Comment by aflack143** [comment]
code pushed

**Comment by CRHarding** [comment]
Ok, you still need the json.loads line in there, un-uncomment it.

**Comment by aflack143** [comment]
it created a user!

I still have the jsondecodeerror on the profiles/create/ though.

**Comment by CRHarding** [comment]
Awesome! Ok, now we're switching from tokens to bitcoin, this looks to be a .5 bitcoin issue right here.

**Comment by CRHarding** [comment]
I'll forward you my address, don't worry about david and leo, they don't have to know...

**Comment by aflack143** [comment]
I am still lost about all this bitcoin business

**Comment by CRHarding** [comment]
Ok, so now we're back to where we started, so if you look at the error it's interesting that the error is being thrown in the GET route, the POST is throwing a 200 status which is solid, it's a GET route that initially throws a 500.

**Comment by CRHarding** [comment]
Which is interesting because you're posting from react, so why is it doing an initial GET request?

**Comment by CRHarding** [comment]
That error is only thrown when you hit the submit button? Or is it thrown when you refresh the page?

**Comment by aflack143** [comment]
its the error when I try to reach profile/create/ in django server

**Comment by CRHarding** [comment]
Hold on, though, are you clicking the submit button?

**Comment by CRHarding** [comment]
Walk us through the steps you go through before you get to the error.

**Comment by aflack143** [comment]
can I share it with you?

**Comment by CRHarding** [comment]
Share it? If you could just go through the steps to recreate the issue, we're making this as much as possible a mimic of the average work place.

**Comment by aflack143** [comment]
I don't do anything before it - I get the message when I try to go to this page: http://localhost:8000/profiles/create/

**Comment by CRHarding** [comment]
Wait, why are you using your browser to go to localhost:8000? Shouldn't you be hitting your react app and using the signup page to send the post request?

**Comment by aflack143** [comment]
I was trying to make sure all links were working

**Comment by CRHarding** [comment]
Ah, gotcha, ok so you don't have a GET request set up for your /profiles/create, and by default browsers only send GET requests via the address bar, so you can't test that route using a browser, you'd have to test it using postman.

**Comment by aflack143** [comment]
oh ok - that doesn't work on my AWS, makes sense

**Comment by CRHarding** [comment]
Awesome, so I'm going to close this beauty of an issue ticket because it seems to be resolved!

**Comment by CRHarding** [comment]
nm, this is your repo, feel free to close this whenever.
