### ISSUE TITLE
Country Visited update not working and delete not removing user

### ISSUE THREAD

**Issue by aflack143** [aflack143/world_spectacular_backend#2]
I was trying to set up the sub on the User_Visited.js like I did on all the other pages and I keep getting this error:
TypeError: Cannot destructure property 'sub' of 'user' as it is undefined.

This error is 1 of issues linked to the update_visit not working.
I can only call Auth0 from a function component, so I made a User_visit component to meet this requirement.

I have pushed my codes.

**Comment by davidmagbee** [comment]
What have you tried so far? @aflack143 

Can you list the specific files you're working in and ideally lines where the code is throwing errors?

Much easier for us to assist you with the requested issue ticket information. Thanks!

**Comment by aflack143** [comment]
sorry, I took break for the kids.

the react issue pages stem from country.js / user_visit.js / profile.js - that is where these buttons are stored.

**Comment by aflack143** [comment]
I got the sub to appear correctly - but still not connecting my update/deletes  (trying to push new frontend code)

**Comment by CRHarding** [comment]
Ping us here when you're able to push and we'll give it a look.

**Comment by aflack143** [comment]
its pushed now

**Comment by CRHarding** [comment]
Oh, wait, this issue is on your backend repo?

**Comment by davidmagbee** [comment]
Okay, can you further clarify the issue you're currently having?

**Comment by davidmagbee** [comment]
Can you be specific about files associated with the issue and lines of code (if you are getting that in your issue). This is ultimately to be of better help to you. Thanks @aflack143

**Comment by aflack143** [comment]
I am not getting it to complete the post/delete requests for the user_visited view

**Comment by CRHarding** [comment]
What errors are you running into?

**Comment by aflack143** [comment]
I can't figure it out, I am not even connecting - and on page refresh I am getting the sub error again.

**Comment by CRHarding** [comment]
No, the error codes you're getting, what do you mean by sub error, we need some screen shots or specific error text and some line numbers that you're zeroing in on.

**Comment by aflack143** [comment]
![image](https://user-images.githubusercontent.com/80013194/125845381-f083640d-0626-41b3-95a6-d16da141c744.png)

**Comment by CRHarding** [comment]
Alright, so what is that error telling you? Whenever you see a Cannot read property 'x' of undefined it means that your x is not being set properly. First thing I would do is verify that I spelled it correctly with correct casing, and from there I would check into where I'm setting that variable.

**Comment by aflack143** [comment]
its being drawn from the userauth0 - it works on the other pages but is being a problem on this page.

**Comment by CRHarding** [comment]
So uservisitedCountries.sub works on all other pages but this one?

**Comment by CRHarding** [comment]
And it's spelled the same, and the casing is the same in every other page as well as this one?

**Comment by aflack143** [comment]
I never had to define it that far - I have only ever had to use sub but this page is not working with it.

**Comment by CRHarding** [comment]
I am very confused by what this sub is you're referring to.

**Comment by aflack143** [comment]
![image](https://user-images.githubusercontent.com/80013194/125845988-018a42db-4a68-4428-9b7c-d138f2411046.png)
 its from the AuthO - I can but the sub with is the unique key for the authentication

**Comment by CRHarding** [comment]
Based on that screenshot, you have uservisitedCountries.sub in previous screenshot, in this one you have userVisitedCountries...

**Comment by CRHarding** [comment]
<img width="165" alt="Screen Shot 2021-07-15 at 3 28 16 PM" src="https://user-images.githubusercontent.com/34920615/125846279-58506a37-ea02-426e-8fab-cc8e3acf93dd.png">

**Comment by CRHarding** [comment]
<img width="215" alt="Screen Shot 2021-07-15 at 3 28 33 PM" src="https://user-images.githubusercontent.com/34920615/125846298-6ba5fe5c-e687-48a3-bc18-4f2011d98ad9.png">

**Comment by aflack143** [comment]
I am trying to push the updated code

**Comment by CRHarding** [comment]
One thing I see is that you have const sub = user; in the UserVisit.js component, but you have const { sub } = user in the other ones.

**Comment by CRHarding** [comment]
For example in Profile.js you have:

const { user } = useAuth0();
 const { sub, picture } = user;

**Comment by aflack143** [comment]
I have been trying to change it based on console.logs - I have a post staring to appear on the django log - but its not active

**Comment by davidmagbee** [comment]
Can you clarify your comment above? @aflack143

**Comment by aflack143** [comment]
my post/delete are working - but on reloading the page the sub stops working

and now that I am testing it all again, my user create is not working again - it is not even getting to django

**Comment by CRHarding** [comment]
On page reload makes sense, you're trying to restart the application in the middle of the process, as long as you can start from your root route and go from there don't worry about it.

In terms of the create you've got to give us a little more to go off of. Are there errors? If so what are the errors?

**Comment by aflack143** [comment]
![image](https://user-images.githubusercontent.com/80013194/125854443-80f5776f-ba02-4257-9cfb-1564c8104d4c.png)

**Comment by CRHarding** [comment]
You said it's not getting to django, that error is being thrown by django, do you mean that it's not creating correctly in django?

**Comment by aflack143** [comment]
I was not getting response to populate into django - I did a print(response) on the top line of view

**Comment by aflack143** [comment]
![image](https://user-images.githubusercontent.com/80013194/125855255-eced818d-182b-4894-9d7d-54cc743a9a38.png)


but I console log the profile data before I send it and thats coming over correctly

**Comment by CRHarding** [comment]
The error is coming from the get_user function, user = User.objects.get(token=token) but you said you're getting this error when you're trying to create a user?

**Comment by aflack143** [comment]
if the user is not in the system - this is the screen non profile users get: 
![image](https://user-images.githubusercontent.com/80013194/125856907-03c9f23b-e25f-400c-b095-74f742ace848.png)

**Comment by aflack143** [comment]
and users who have created profiles get this screen: 
![image](https://user-images.githubusercontent.com/80013194/125857099-7d9df9c3-8fec-453b-bec9-3cfe6eb300d6.png)

**Comment by CRHarding** [comment]
Yeah, but if you look at the error you're 500 on a GET route for /profiles/(some oauth data here), THEN you're getting a 500 error on the POST route to create a user.

**Comment by CRHarding** [comment]
When I'd assume the POST route should be hitting first, no?

**Comment by aflack143** [comment]
no, they are on the same page - it looks to see if there is a uwer profile before determining if it needs to render create of display

**Comment by aflack143** [comment]
what am I missing in my get code?

**Comment by aflack143** [comment]
It is crunch time, I am nervous about this.

**Comment by CRHarding** [comment]
We have no clue, there is far too much complexity in each student's application for us to be able to look at one fifteen line file and diagnose it. The expectation is that you put what you can into it and see where things go. This is why issue tickets are so important with clearly arranged ideas on what you're trying to do, what errors you're encountering, screenshots of all relevant pieces, specific lines of code that you've narrowed it down to.

We definitely understand that it's crunch time, but whatever features you're not able to get to put them aside and only show code that works. The presentation isn't meant to be the end of the project, it's meant to be a launching off place.

Don't stress about the pieces that you don't finish, focus on what is there currently and how you can polish it and get it looking good before tomorrow. I promise you that tomorrow is not the make or break part of your career, every student is going to spend some time walking through their application, is going to show their code, and we're going to applaud and move on. Tara et all know you've only been programming for 3 months, that's zero time, literally no time at all. They're looking for students who tried to tackle something interesting and came away with a good starting place from which they can mentor / grow.

**Comment by CRHarding** [comment]
Each student now has 4-5 thousand lines of code with various dependencies and different logic going, there is absolutely no way for us to jump into a codebase without some sort of background without it taking hours on up to a day or two.

And the same will go for when you're working on a team, you're manager will have a team to oversee and won't be able to hop into a code base without some idea of what's going on. That's why we're pushing so hard on this now, to move you all into a mindset where you push as far as you can and document as much as you can and when you hit the brick wall you have a concise and well-written issue that your boss can look at and snuff out the error in an hour or so rather than it taking a day or more.

**Comment by aflack143** [comment]
I can fake it until I make it! 
I had a mishap on the 1st project and spun that into an "intentional" design.

Thanks for looking at it with me, I was close on each of them, restarting the server seems to be the most important part of updating code, the final updates fixed the update/delete buttons.

**Comment by CRHarding** [comment]
Now we're talking!! I love the intentional design 🥇 ! And absolutely, it's going to be something you'll find in a second when you glance back on this further down the road. And good to hear about the update / delete!
